verbose: true
constant:
  Url: U
  ActiveRecord::Base: AB

instance_method:
  Url:
    tag_add_and_remove: tar
    tag_remove_and_save: tr
    tag_add_and_save: ta
    tag_and_save: t
    tag_list: tl
  ActiveRecord::Base:
    update_attribute: ua
  HasMachineTags::NamespaceGroup:
    outline_view: ov

class_method:
  Tag:
    machine_tags: mt
    namespaces: nsps
    predicates: ps
    values: vs
    
  Url:
    tagged_with: tw
    tagged_with_count: twc
    find_and_change_machine_tags: fcmt
  ActiveRecord::Base:
    find: '[]'
    destroy: d