verbose: true
constant:
  Url: U
  ActiveRecord::Base: AB
  Tag: T
instance_method:
  Url:
    tag_add_and_remove: tar
    tag_remove_and_save: tr
    tag_add_and_save: ta
    tag_and_save: t
    tag_list: tl
  ActiveRecord::Base:
    update_attribute: ua
  HasMachineTags::NamespaceGroup:
    outline_view: ov
  ConsoleUpdate::SingletonMethods:
    console_update: cu
  ConsoleUpdate::NamedScope:
    console_update: cu
class_method:
  Tag:
    machine_tags: mt
    namespaces: nsps
    predicates: ps
    values: vs
  Url:
    tagged_with: tw
    tagged_with_count: twc
    find_and_change_machine_tags: fcmt
  ActiveRecord::Base:
    find: '[]'
    destroy: d
delegate_to_class_method:
  ConsoleMethods:
    - - trn
      - Tag
      - find_name_by_regexp
    - - tn
      - Tag
      - find_by_name
    - - mtrn
      - Tag
      - search_machine_tag_names
    - - uc
      - Url
      - quick_create
    - - urn
      - Url
      - find_name_by_regexp