commands:
  table: 
    description: displays an ascii table via hirb
  view: 
    description: displays a hirb view
  open_url:
    description: open with browser
  clip_url:
    description: copy urls into osx clipboard
  rename_tag:
    description: renames tag
  list:
    description: lists all commands
  search:
    description: search commands by name
  trn:
    description: find tags with regex string
  mtrn:
    description: find tags within machine tag fields with regex string
  uc:
    description: quickly create a url
  urn:
    description: search urls with regex string
  ut:
    description: find urls with wildcard machine tag
  uf:
    description: find urls by wildcard or ids
  mtr:
    description: reload machine tag config
  tag_tree:
    description: machine tag tree from wildcard machine tag
  